name: RetroArch Assets Bundle

on:
  # Trigger the workflow on push,
  # but only for the master branch
  push:
    branches:
      - master
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Assets:
    name: Bundle Assets for RetroArch
    runs-on: ubuntu-latest

    steps:
    - run: rm -rf branding wallapper/* .git
    - run 7z a -mx=9 assets.7z *
    - name: Upload assets bundle
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: assets.7z
        tag: Latest
        asset_name: assets.7z
        overwrite: true
